version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - big-data-network

  airflow-init:
    build: .
    image: custom-airflow:latest
    depends_on:
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW_UID: 50000
    entrypoint: >
      bash -c "
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com
      "
    networks:
      - big-data-network

  airflow-webserver:
    image: custom-airflow:latest
    depends_on:
      - airflow-init
      - postgres
    environment:
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8082
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW_UID: 50000
    ports:
      - "8082:8082"
    command: "airflow webserver"
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - big-data-network

  airflow-scheduler:
    image: custom-airflow:latest
    user: "50000:1001"
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW_UID: 50000
    command: "airflow scheduler"
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - big-data-network

volumes:
  postgres-db-volume:

networks:
  big-data-network:
    external: true